# Generated by Django 3.0.4 on 2020-04-10 16:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisineName', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('tags', jsonfield.fields.JSONField()),
            ],
        ),
    ]
