# Generated by Django 3.0.4 on 2020-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.CharField(default='200', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='cuisineType',
            field=models.CharField(default='Breakfast', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
