# Generated by Django 3.0.4 on 2020-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200411_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo2',
            field=models.CharField(default='menu/images/breakfast/idly.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
