# Generated by Django 3.0.4 on 2020-04-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='specialitymenu',
            name='cuisineName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialitymenu',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
