# Generated by Django 3.0.4 on 2020-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200412_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
