# Generated by Django 3.0.4 on 2020-04-16 19:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_customer_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='personalised_menu',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
